keys:
  - &hitori age1uw7he6dj45ptsg3xwk5f324wzlcplyh7yxh6vpvux03rpzy76qsqzcjlfx
creation_rules:
  - path_regex: secrets/shared.yaml
    key_groups:
    - age:
      - *hitori
  - path_regex: secrets/hitori.yaml
    key_groups:
    - age:
      - *hitori
