keys:
  - &host_hitori age1gpemxswpk52hyhj6xsutspdtd0zk2qt389wttqd9af9lkx67dp5seqxa6r
creation_rules:
  - path_regex: secrets/shared.yaml
    key_groups:
    - age:
      - *host_hitori
  - path_regex: secrets/hitori.yaml
    key_groups:
    - age:
      - *host_hitori
