keys:
  - &host_hitori age1gpemxswpk52hyhj6xsutspdtd0zk2qt389wttqd9af9lkx67dp5seqxa6r
  - &ikuyo age1m2thhfj6d8m7akz6ud7w525v4rvz9dml6f9g22xd5khed2fafqyq8tjun4
creation_rules:
  - path_regex: secrets/shared.yaml
    key_groups:
    - age:
      - *host_hitori
      - *ikuyo
  - path_regex: secrets/hitori.yaml
    key_groups:
    - age:
      - *host_hitori
  - path_regex: secrets/ikuyo.yaml
    key_groups:
    - age:
      - *ikuyo
