theme = "catppuccin_mocha_nobg"

[editor]
scrolloff = 3
mouse = true
middle-click-paste = false
scroll-lines = 1
shell = ["sh", "-c"]
line-number = "absolute"
cursorline = false
cursorcolumn = false
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 300
completion-trigger-len = 1
auto-info = true
true-color = true
rulers = []
bufferline = "never"
color-modes = true

[editor.statusline]
left = ["mode"]
center = ["spacer"]
right = ["spacer"]
separator = "+"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
max-depth = 1

[editor.auto-pairs]
"(" = ")"
"{" = "}"
"[" = "]"
"'" = "'"
'"' = '"'
"`" = "`"
"<" = ">"

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 0
